<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str; 

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Xóa sạch dữ liệu
        // Phải xóa bảng "con" (variant) trước, rồi mới xóa bảng "cha" (product)
        DB::table('product_variant')->truncate();
        DB::table('product')->truncate();

        // Tạo product (Tên chung)
        DB::table('product')->insert([

            // DỤNG CỤ TẬP LUYỆN (category_id = 1) 
            // 7 sản phẩm
            [
                'product_name' => 'Tạ Kettebell', 
                'description' => 'Tạ ấm Kettebell chất liệu gang bọc vinyl, nhiều trọng lượng và màu sắc. Phù hợp cho các bài tập toàn thân.',
                'image_url' => 'https://res.cloudinary.com/dna9qbejm/image/upload/v1763041390/Shop_1_ojpoor.png',
                'slug' => Str::slug('Tạ Kettebell'),
                'category_id' => 1,
                'brand' => 'Generic',
                'origin' => 'Việt Nam',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Thảm tập Yoga',
                'description' => 'Thảm tập Yoga TPE, dày 6mm, chống trượt 2 mặt, có vạch định tuyến, nhiều màu.',
                'image_url' => 'https://res.cloudinary.com/dna9qbejm/image/upload/v1763042326/Shop_2_kcbi3y.png',
                'slug' => Str::slug('Thảm tập Yoga'),
                'category_id' => 1,
                'brand' => 'Liforme',
                'origin' => 'Anh Quốc',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Dây nhảy không dây',
                'description' => 'Dây nhảy tiện lợi cho tập trong không gian nhỏ, có đồng hồ đếm số lần nhảy.',
                'image_url' => 'https://res.cloudinary.com/dna9qbejm/image/upload/v1763042700/Shop_3_espkkp.png',
                'slug' => Str::slug('Dây nhảy không dây'),
                'category_id' => 1,
                'brand' => 'Aolikes',
                'origin' => 'Trung Quốc',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Bộ 2 tạ tay Vinyl Reefit',
                'description' => 'Bộ tạ tay bọc vinyl chống trơn trượt, màu sắc nổi bật, thương hiệu uy tín.',
                'image_url' => 'https://res.cloudinary.com/dna9qbejm/image/upload/v1763043509/Shop_5_vfdqt5.png',
                'slug' => Str::slug('Tạ tay Vinyl Reefit'),
                'category_id' => 1,
                'brand' => 'Reefit',
                'origin' => 'Việt Nam',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Tạ tay bọc cao su',
                'description' => 'Tạ tay bọc cao su cao cấp, lõi gang, tay cầm mạ chrome.',
                'image_url' => 'https://res.cloudinary.com/dna9qbejm/image/upload/v1763043514/Shop_6_tl7a7c.png',
                'slug' => Str::slug('Tạ tay bọc cao su'),
                'category_id' => 1,
                'brand' => 'Generic',
                'origin' => 'Trung Quốc',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Tạ tay lục giác',
                'description' => 'Kết hợp hoàn hảo giữa tập luyện và thẩm mỹ. Tạ tay lục giác mang đến cảm hứng tập luyện mỗi ngày ngay tại không gian sống của bạn.',
                'image_url' => 'https://res.cloudinary.com/dna9qbejm/image/upload/v1763043415/Shop_4_sc1uok.png',
                'slug' => Str::slug('Tạ tay lục giác'),
                'category_id' => 1,
                'brand' => 'Generic',
                'origin' => 'Trung Quốc',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Dây kháng lực (Bộ 5 dây)',
                'description' => 'Bộ 5 dây kháng lực với 5 mức độ khác nhau, giúp tăng lực cơ tay, vai, lưng, chân, hỗ trợ tập Squat.',
                'image_url' => 'https://res.cloudinary.com/dna9qbejm/image/upload/v1763043773/Shop_7_bvhh78.png',
                'slug' => Str::slug('Dây kháng lực Bộ 5 dây'),
                'category_id' => 1,
                'brand' => 'Aolikes',
                'origin' => 'Trung Quốc',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // THỰC PHẨM BỔ SUNG (category_id = 2)
            [
                'product_name' => 'Whey Protein Gold Standard 100%', 
                'description' => 'Whey Protein bán chạy nhất thế giới. Cung cấp 24g Protein mỗi lần dùng. Hỗ trợ tăng cơ, phục hồi sau tập.',
                'image_url' => 'https://res.cloudinary.com/dna9qbejm/image/upload/v1763044017/Shop_8_excsio.png',
                'slug' => Str::slug('Whey Protein Gold Standard 100%'),
                'category_id' => 2,
                'brand' => 'Optimum Nutrition',
                'origin' => 'Mỹ (USA)', 
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'C4 Pre-Workout Original',
                'description' => 'Tăng sức mạnh, tỉnh táo trước khi tập (Pre-workout). Nhiều hương vị.',
                'image_url' => 'https://res.cloudinary.com/dna9qbejm/image/upload/v1763044206/Shop_9_nf5x0m.png',
                'slug' => Str::slug('C4 Pre-Workout Original'),
                'category_id' => 2,
                'brand' => 'Cellucor',
                'origin' => 'Mỹ (USA)',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Dầu cá Omega 3',
                'description' => 'Bổ sung Omega 3, tốt cho tim mạch, mắt và não bộ.',
                'image_url' => 'https://res.cloudinary.com/dna9qbejm/image/upload/v1763044213/Shop_10_yfh8aw.png',
                'slug' => Str::slug('Dầu cá Omega 3'),
                'category_id' => 2,
                'brand' => 'Now Foods',
                'origin' => 'Mỹ (USA)',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Vitamin Tổng Hợp (Opti-Men)',
                'description' => 'Vitamin tổng hợp dành cho nam giới, tăng cường sức khỏe.',
                'image_url' => 'https://res.cloudinary.com/dna9qbejm/image/upload/v1763044289/Shop_11_qt4kgq.png',
                'slug' => Str::slug('Vitamin Tổng Hợp Opti-Men'),
                'category_id' => 2,
                'brand' => 'Optimum Nutrition',
                'origin' => 'Mỹ (USA)',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Mass Gainer (Serious Mass)', 
                'description' => 'Sữa tăng cân nhanh, giúp phát triển cơ bắp, cung cấp 1250 calo mỗi lần dùng.',
                'image_url' => 'https://res.cloudinary.com/dna9qbejm/image/upload/v1763044719/Shop_13_yii4wr.png',
                'slug' => Str::slug('Mass Gainer Serious Mass'),
                'category_id' => 2,
                'brand' => 'Optimum Nutrition',
                'origin' => 'Mỹ (USA)',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Thanh Protein Zero Bar (20 thanh)',
                'description' => 'Bữa ăn nhẹ thay thế, 20g Protein mỗi thanh, tiện lợi mang đi.',
                'image_url' => 'https://res.cloudinary.com/dna9qbejm/image/upload/v1763044394/Shop_12_thzsbf.png',
                'slug' => Str::slug('Thanh Protein Zero Bar'),
                'category_id' => 2,
                'brand' => 'Biotech',
                'origin' => 'Mỹ (USA)',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // QUẦN ÁO THỂ THAO (category_id = 3)
            [
                'product_name' => 'Giày Nike Metcon',
                'description' => 'Giày tập luyện đa năng Nike Metcon, phù hợp cho chạy bộ, tập tạ và các bài tập cường độ cao.',
                'image_url' => 'https://res.cloudinary.com/dna9qbejm/image/upload/v1763044856/Shop_15_nckkgz.png',
                'slug' => Str::slug('Giày Nike Metcon'),
                'category_id' => 3,
                'brand' => 'Nike',
                'origin' => 'Việt Nam',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Bộ đồ tập Tracksuit',
                'description' => 'Bộ đồ thể thao (tracksuit) gồm áo khoác và quần dài, chất liệu thoáng mát, co giãn tốt.',
                'image_url' => 'https://res.cloudinary.com/dna9qbejm/image/upload/v1763044855/Shop_14_dum3kn.png',
                'slug' => Str::slug('Bộ đồ tập Tracksuit'),
                'category_id' => 3,
                'brand' => 'Adidas',
                'origin' => 'Việt Nam',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Áo Thun Tập Gym Nam',
                'description' => 'Áo thun co giãn 4 chiều, siêu thoáng mát, phù hợp cho tập gym và thể thao.',
                'image_url' => 'https://res.cloudinary.com/dna9qbejm/image/upload/v1763045685/Shop_19_mrlflt.png',
                'slug' => Str::slug('Áo Thun Tập Gym Nam'),
                'category_id' => 3,
                'brand' => 'Adidas',
                'origin' => 'Thái Lan',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Quần Short Tập Gym Nam 2 Lớp',
                'description' => 'Quần short 2 lớp, có túi đựng điện thoại bên trong, vải dù thoáng khí.',
                'image_url' => 'https://res.cloudinary.com/dna9qbejm/image/upload/v1763045160/Shop_16_hsewdx.png',
                'slug' => Str::slug('Quần Short Tập Gym Nam 2 Lớp'),
                'category_id' => 3,
                'brand' => 'GymShark',
                'origin' => 'Trung Quốc',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Quần Legging Nữ Cạp Cao',
                'description' => 'Quần legging tập gym, cạp cao gen bụng, chất vải dày dặn, không lộ.',
                'image_url' => 'https://res.cloudinary.com/dna9qbejm/image/upload/v1763045366/Shop_17_pbgrsm.png',
                'slug' => Str::slug('Quần Legging Nữ Cạp Cao'),
                'category_id' => 3,
                'brand' => 'Lululemon',
                'origin' => 'Canada',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Set 4 Vớ Thể Thao', 
                'description' => 'Vớ cổ cao, chất cotton dày, thấm hút mồ hôi, chống trượt.',
                'image_url' => 'https://res.cloudinary.com/dna9qbejm/image/upload/v1763045373/Shop_18_rid3r0.png',
                'slug' => Str::slug('Tất Vớ Cổ Cao Thể Thao'),
                'category_id' => 3,
                'brand' => 'Nike',
                'origin' => 'Việt Nam',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // PHỤ KIỆN THỂ THAO (category_id = 4)
            [
                'product_name' => 'Khăn tập Microfiber', 
                'description' => 'Khăn tập thể thao chuyên dụng, chất liệu microfiber siêu thấm hút, khô nhanh.',
                'image_url' => 'https://res.cloudinary.com/dna9qbejm/image/upload/v1763045986/Shop_20_xh65nw.png',
                'slug' => Str::slug('Khăn tập Microfiber'),
                'category_id' => 4,
                'brand' => 'Generic',
                'origin' => 'Trung Quốc',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Bình nước La Pro',
                'description' => 'Bình nước thể thao, nhựa Tritan (BPA-Free), có vạch chia ml, nhiều màu sắc.',
                'image_url' => 'https://res.cloudinary.com/dna9qbejm/image/upload/v1763045996/Shop_21_wwhld9.png',
                'slug' => Str::slug('Bình nước La Pro'),
                'category_id' => 4,
                'brand' => 'La Pro',
                'origin' => 'Hàn Quốc',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Túi đựng đồ thể thao',
                'description' => 'Túi thể thao (duffel bag), có ngăn đựng giày riêng, chống nước, chống bụi.',
                'image_url' => 'https://res.cloudinary.com/dna9qbejm/image/upload/v1763046038/Shop_22_phtubr.png',
                'slug' => Str::slug('Túi đựng đồ thể thao'),
                'category_id' => 4,
                'brand' => 'Generic',
                'origin' => 'Việt Nam',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Găng tay tập Gym',
                'description' => 'Găng tay tập tạ, có đệm lót, có hoặc không có dây quấn bảo vệ cổ tay.',
                'image_url' => 'https://res.cloudinary.com/dna9qbejm/image/upload/v1763046242/Shop_24_azlpqq.png',
                'slug' => Str::slug('Găng tay tập Gym'),
                'category_id' => 4,
                'brand' => 'Adidas',
                'origin' => 'Trung Quốc',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Đai lưng mềm tập Gym',
                'description' => 'Đai lưng bản to, lõi xốp, hỗ trợ gồng lưng khi Squat, Deadlift.',
                'image_url' => 'https://res.cloudinary.com/dna9qbejm/image/upload/v1763046447/Shop_25_mbn0z8.png',
                'slug' => Str::slug('Đai lưng mềm tập Gym'),
                'category_id' => 4,
                'brand' => 'Valeo',
                'origin' => 'Trung Quốc',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_name' => 'Băng bảo vệ gối', 
                'description' => 'Bảo vệ gối khi Squat nặng, co giãn đàn hồi, thoáng khí.',
                'image_url' => 'https://res.cloudinary.com/dna9qbejm/image/upload/v1763046235/Shop_23_bzi7dr.png',
                'slug' => Str::slug('Băng bảo vệ gối'),
                'category_id' => 4,
                'brand' => 'Aolikes',
                'origin' => 'Trung Quốc',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}