<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

use Illuminate\Support\Facades\DB;

class ProductVariantSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Xóa sạch dữ liệu
        DB::table('product_variant')->truncate();

        // Tạo product_variant
        DB::table('product_variant')->insert([

            // === 1. "Tạ tay lục giác" (product_id = 6) ===
            // 6 biến thể
            [
                'product_id' => 6,
                'color' => 'Xanh lá mạ',
                'size' => '2kg',
                'weight' => 2,
                'unit' => 'kg',
                'price' => 99000.00,
                'discount_price' => null,
                'is_discounted' => false,
                'stock' => 50,
                'image_url' => 'https://res.cloudinary.com/dna9qbejm/image/upload/v1763043415/Shop_4_sc1uok.png',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 6,
                'color' => 'Xanh lá mạ',
                'size' => '5kg',
                'weight' => 5,
                'unit' => 'kg',
                'price' => 149000.00,
                'discount_price' => null,
                'is_discounted' => false,
                'stock' => 50,
                'image_url' => 'https://res.cloudinary.com/dna9qbejm/image/upload/v1763043415/Shop_4_sc1uok.png',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 6,
                'color' => 'Vàng',
                'size' => '2kg',
                'weight' => 2,
                'unit' => 'kg',
                'price' => 99000.00,
                'discount_price' => null,
                'is_discounted' => false,
                'stock' => 50,
                'image_url' => 'https://res.cloudinary.com/dna9qbejm/image/upload/v1763056317/Shop_4_1_rrald8.png',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 6,
                'color' => 'Vàng',
                'size' => '5kg',
                'weight' => 5,
                'unit' => 'kg',
                'price' => 149000.00,
                'discount_price' => null,
                'is_discounted' => false,
                'stock' => 50,
                'image_url' => 'https://res.cloudinary.com/dna9qbejm/image/upload/v1763056317/Shop_4_1_rrald8.png',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 6,
                'color' => 'Xanh lá đậm',
                'size' => '10kg',
                'weight' => 10,
                'unit' => 'kg',
                'price' => 289000.00,
                'discount_price' => null,
                'is_discounted' => false,
                'stock' => 50,
                'image_url' => 'https://res.cloudinary.com/dna9qbejm/image/upload/v1763056320/Shop_4_2_pesnkk.png',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 6,
                'color' => 'Xanh lá đậm',
                'size' => '5kg',
                'weight' => 5,
                'unit' => 'kg',
                'price' => 149000.00,
                'discount_price' => null,
                'is_discounted' => false,
                'stock' => 50,
                'image_url' => 'https://res.cloudinary.com/dna9qbejm/image/upload/v1763056320/Shop_4_2_pesnkk.png',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // === 2. "Dây nhảy không dây" (product_id = 3) ===
            // 3 biến thể (3 màu)
            [
                'product_id' => 3,
                'color' => 'Đỏ',
                'size' => null, 
                'weight' => 0.2,
                'unit' => 'kg',
                'price' => 159000.00,
                'discount_price' => 149000.00,
                'is_discounted' => true,
                'stock' => 40,
                'image_url' => 'hhttps://res.cloudinary.com/dna9qbejm/image/upload/v1763056816/Shop_3_2_jmi4ea.png',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 3,
                'color' => 'Hồng',
                'size' => null,
                'weight' => 0.2,
                'unit' => 'kg',
                'price' => 159000.00,
                'discount_price' => null,
                'is_discounted' => false,
                'stock' => 40,
                'image_url' => 'https://res.cloudinary.com/dna9qbejm/image/upload/v1763056683/Shop_3_1_zljdw5.png',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
             [
                'product_id' => 3,
                'color' => 'Xanh dương',
                'size' => null,
                'weight' => 0.2,
                'unit' => 'kg',
                'price' => 159000.00,
                'discount_price' => null,
                'is_discounted' => false,
                'stock' => 40,
                'image_url' => 'https://res.cloudinary.com/dna9qbejm/image/upload/v1763042700/Shop_3_espkkp.png',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            // === 3. "Thảm tập Yoga" (product_id = 2) ===
            // 2 biến thể (2 màu/size)
            [
                'product_id' => 2,
                'color' => 'Tím',
                'size' => '6mm',
                'weight' => 0.8,
                'unit' => 'kg',
                'price' => 399000.00,
                'discount_price' => null,
                'is_discounted' => false,
                'stock' => 100,
                'image_url' => 'https://res.cloudinary.com/dna9qbejm/image/upload/v1763042326/Shop_2_kcbi3y.png',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 2,
                'color' => 'Xanh dương',
                'size' => '6mm',
                'weight' => 0.8,
                'unit' => 'kg',
                'price' => 399000.00,
                'discount_price' => null,
                'is_discounted' => false,
                'stock' => 100,
                'image_url' => 'https://res.cloudinary.com/dna9qbejm/image/upload/v1763057067/Shop_2_1_n2qoqy.png',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // === 4. "Quần Legging Nữ Cạp Cao" (product_id = 18) ===
            // 3 biến thể (3 size/màu)
            [
                'product_id' => 18,
                'color' => 'Xám',
                'size' => 'M',
                'weight' => 0.25,
                'unit' => 'kg',
                'price' => 450000.00,
                'discount_price' => null,
                'is_discounted' => false,
                'stock' => 50,
                'image_url' => 'https://res.cloudinary.com/dna9qbejm/image/upload/v1763045366/Shop_17_pbgrsm.png',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 18,
                'color' => 'Xám',
                'size' => 'L',
                'weight' => 0.25,
                'unit' => 'kg',
                'price' => 450000.00,
                'discount_price' => null,
                'is_discounted' => false,
                'stock' => 50,
                'image_url' => 'https://res.cloudinary.com/dna9qbejm/image/upload/v1763045366/Shop_17_pbgrsm.png',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 18,
                'color' => 'Xám',
                'size' => 'XL',
                'weight' => 0.25,
                'unit' => 'kg',
                'price' => 450000.00,
                'discount_price' => null,
                'is_discounted' => false,
                'stock' => 40,
                'image_url' => 'https://res.cloudinary.com/dna9qbejm/image/upload/v1763045366/Shop_17_pbgrsm.png',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // === 5. "Quần Short Tập Gym Nam 2 Lớp" (product_id = 17) ===
            // 2 biến thể (2 size)
            [
                'product_id' => 17,
                'color' => 'Đen',
                'size' => 'L',
                'weight' => 0.3,
                'unit' => 'kg',
                'price' => 350000.00,
                'discount_price' => null,
                'is_discounted' => false,
                'stock' => 70,
                'image_url' => 'https://res.cloudinary.com/dna9qbejm/image/upload/v1763045160/Shop_16_hsewdx.png',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 17,
                'color' => 'Đen',
                'size' => 'XL',
                'weight' => 0.3,
                'unit' => 'kg',
                'price' => 350000.00,
                'discount_price' => null,
                'is_discounted' => false,
                'stock' => 70,
                'image_url' => 'https://res.cloudinary.com/dna9qbejm/image/upload/v1763045160/Shop_16_hsewdx.png',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // === 6. "Bình nước La Pro" (product_id = 21) ===
            // 3 biến thể (3 màu/size)
            [
                'product_id' => 21,
                'color' => 'Xanh nhạt',
                'size' => '1000ml',
                'weight' => 0.2,
                'unit' => 'kg',
                'price' => 109000.00,
                'discount_price' => null,
                'is_discounted' => false,
                'stock' => 150,
                'image_url' => 'https://res.cloudinary.com/dna9qbejm/image/upload/v1763045996/Shop_21_wwhld9.png',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 21,
                'color' => 'Hồng phấn',
                'size' => '1800ml',
                'weight' => 0.2,
                'unit' => 'kg',
                'price' => 179000.00,
                'discount_price' => null,
                'is_discounted' => false,
                'stock' => 150,
                'image_url' => 'https://res.cloudinary.com/dna9qbejm/image/upload/v1763057563/Shop_21_1_bae6y4.png',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 21,
                'color' => 'Đen',
                'size' => '1500ml',
                'weight' => 0.25,
                'unit' => 'kg',
                'price' => 149000.00,
                'discount_price' => null,
                'is_discounted' => false,
                'stock' => 100,
                'image_url' => 'https://res.cloudinary.com/dna9qbejm/image/upload/v1763057790/Shop_21_2_honaer.png',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

        ]);
    }
}