<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

use Illuminate\Support\Facades\DB;

class ProductVariantSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Xóa sạch dữ liệu
        DB::table('product_variant')->truncate();

        // Tạo product_variant
        DB::table('product_variant')->insert([

            // === 1. "Tạ Kettebell" (product_id = 1) ===
            [
                'product_id' => 1,
                'color' => 'Hồng',
                'size' => '4kg',
                'weight' => 4,
                'unit' => 'kg',
                'price' => 220000.00,
                'discount_price' => null,
                'is_discounted' => false,
                'stock' => 50,
                'image_url' => 'https://res.cloudinary.com/dna9qbejm/image/upload/v1763041390/Shop_1_ojpoor.png',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // === 2. "Thảm tập Yoga" (product_id = 2) ===
            [
                'product_id' => 2,
                'color' => 'Tím',
                'size' => '6mm',
                'weight' => 0.8,
                'unit' => 'kg',
                'price' => 399000.00,
                'discount_price' => null,
                'is_discounted' => false,
                'stock' => 100,
                'image_url' => 'https://res.cloudinary.com/dna9qbejm/image/upload/v1763042326/Shop_2_kcbi3y.png',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 2,
                'color' => 'Xanh dương',
                'size' => '6mm',
                'weight' => 0.8,
                'unit' => 'kg',
                'price' => 399000.00,
                'discount_price' => null,
                'is_discounted' => false,
                'stock' => 100,
                'image_url' => 'https://res.cloudinary.com/dna9qbejm/image/upload/v1763057067/Shop_2_1_n2qoqy.png',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // === 3. "Dây nhảy không dây" (product_id = 3) ===
            [
                'product_id' => 3,
                'color' => 'Đỏ',
                'size' => null, 
                'weight' => 0.2,
                'unit' => 'kg',
                'price' => 159000.00,
                'discount_price' => 149000.00,
                'is_discounted' => true,
                'stock' => 40,
                'image_url' => 'https://res.cloudinary.com/dna9qbejm/image/upload/v1763056816/Shop_3_2_jmi4ea.png',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 3,
                'color' => 'Hồng',
                'size' => null,
                'weight' => 0.2,
                'unit' => 'kg',
                'price' => 159000.00,
                'discount_price' => null,
                'is_discounted' => false,
                'stock' => 40,
                'image_url' => 'https://res.cloudinary.com/dna9qbejm/image/upload/v1763056683/Shop_3_1_zljdw5.png',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 3,
                'color' => 'Xanh dương',
                'size' => null,
                'weight' => 0.2,
                'unit' => 'kg',
                'price' => 159000.00,
                'discount_price' => null,
                'is_discounted' => false,
                'stock' => 40,
                'image_url' => 'https://res.cloudinary.com/dna9qbejm/image/upload/v1763042700/Shop_3_espkkp.png',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // === 4. "Bộ 2 tạ tay Vinyl Reefit" (product_id = 4) ===
            [
                'product_id' => 4,
                'color' => 'Xanh',
                'size' => '1kg (x2)',
                'weight' => 2,
                'unit' => 'kg',
                'price' => 150000.00,
                'discount_price' => null,
                'is_discounted' => false,
                'stock' => 30,
                'image_url' => 'https://res.cloudinary.com/dna9qbejm/image/upload/v1763043509/Shop_5_vfdqt5.png',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // === 5. "Tạ tay bọc cao su" (product_id = 5) ===
            [
                'product_id' => 5,
                'color' => 'Đen',
                'size' => '5kg',
                'weight' => 5,
                'unit' => 'kg',
                'price' => 350000.00,
                'discount_price' => null,
                'is_discounted' => false,
                'stock' => 20,
                'image_url' => 'https://res.cloudinary.com/dna9qbejm/image/upload/v1763043514/Shop_6_tl7a7c.png',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // === 6. "Tạ tay lục giác" (product_id = 6) ===
            [
                'product_id' => 6,
                'color' => 'Xanh lá mạ',
                'size' => '2kg',
                'weight' => 2,
                'unit' => 'kg',
                'price' => 99000.00,
                'discount_price' => null,
                'is_discounted' => false,
                'stock' => 50,
                'image_url' => 'https://res.cloudinary.com/dna9qbejm/image/upload/v1763043415/Shop_4_sc1uok.png',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 6,
                'color' => 'Xanh lá mạ',
                'size' => '5kg',
                'weight' => 5,
                'unit' => 'kg',
                'price' => 149000.00,
                'discount_price' => null,
                'is_discounted' => false,
                'stock' => 50,
                'image_url' => 'https://res.cloudinary.com/dna9qbejm/image/upload/v1763043415/Shop_4_sc1uok.png',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 6,
                'color' => 'Vàng',
                'size' => '2kg',
                'weight' => 2,
                'unit' => 'kg',
                'price' => 99000.00,
                'discount_price' => null,
                'is_discounted' => false,
                'stock' => 50,
                'image_url' => 'https://res.cloudinary.com/dna9qbejm/image/upload/v1763056317/Shop_4_1_rrald8.png',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 6,
                'color' => 'Vàng',
                'size' => '5kg',
                'weight' => 5,
                'unit' => 'kg',
                'price' => 149000.00,
                'discount_price' => null,
                'is_discounted' => false,
                'stock' => 50,
                'image_url' => 'https://res.cloudinary.com/dna9qbejm/image/upload/v1763056317/Shop_4_1_rrald8.png',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 6,
                'color' => 'Xanh lá đậm',
                'size' => '10kg',
                'weight' => 10,
                'unit' => 'kg',
                'price' => 289000.00,
                'discount_price' => null,
                'is_discounted' => false,
                'stock' => 50,
                'image_url' => 'https://res.cloudinary.com/dna9qbejm/image/upload/v1763056320/Shop_4_2_pesnkk.png',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 6,
                'color' => 'Xanh lá đậm',
                'size' => '5kg',
                'weight' => 5,
                'unit' => 'kg',
                'price' => 149000.00,
                'discount_price' => null,
                'is_discounted' => false,
                'stock' => 50,
                'image_url' => 'https://res.cloudinary.com/dna9qbejm/image/upload/v1763056320/Shop_4_2_pesnkk.png',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // === 7. "Dây kháng lực (Bộ 5 dây)" (product_id = 7) ===
            [
                'product_id' => 7,
                'color' => 'Nhiều màu',
                'size' => 'Bộ 5 dây',
                'weight' => 0.4,
                'unit' => 'kg',
                'price' => 199000.00,
                'discount_price' => null,
                'is_discounted' => false,
                'stock' => 100,
                'image_url' => 'https://res.cloudinary.com/dna9qbejm/image/upload/v1763043773/Shop_7_bvhh78.png',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // === 8. "Whey Protein Gold Standard 100%" (product_id = 8) ===
            [
                'product_id' => 8,
                'color' => 'Double Rich Chocolate',
                'size' => '5 Lbs',
                'weight' => 2.27,
                'unit' => 'kg',
                'price' => 1650000.00,
                'discount_price' => 1550000.00,
                'is_discounted' => true,
                'stock' => 50,
                'image_url' => 'https://res.cloudinary.com/dna9qbejm/image/upload/v1763044017/Shop_8_excsio.png',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // === 9. "C4 Pre-Workout Original" (product_id = 9) ===
            [
                'product_id' => 9,
                'color' => 'Icy Blue Razz', // Vị
                'size' => '30 Lần dùng',
                'weight' => 0.195,
                'unit' => 'kg',
                'price' => 750000.00,
                'discount_price' => null,
                'is_discounted' => false,
                'stock' => 60,
                'image_url' => 'https://res.cloudinary.com/dna9qbejm/image/upload/v1763044206/Shop_9_nf5x0m.png',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // === 10. "Dầu cá Omega 3" (product_id = 10) ===
            [
                'product_id' => 10,
                'color' => null, // Không có vị/màu
                'size' => '100 viên',
                'weight' => 0.2,
                'unit' => 'kg',
                'price' => 450000.00,
                'discount_price' => null,
                'is_discounted' => false,
                'stock' => 100,
                'image_url' => 'https://res.cloudinary.com/dna9qbejm/image/upload/v1763044213/Shop_10_yfh8aw.png',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // === 11. "Vitamin Tổng Hợp (Opti-Men)" (product_id = 11) ===
            [
                'product_id' => 11,
                'color' => null,
                'size' => '90 viên',
                'weight' => 0.15,
                'unit' => 'kg',
                'price' => 550000.00,
                'discount_price' => null,
                'is_discounted' => false,
                'stock' => 70,
                'image_url' => 'https://res.cloudinary.com/dna9qbejm/image/upload/v1763044289/Shop_11_qt4kgq.png',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // === 12. "Mass Gainer (Serious Mass)" (product_id = 12) ===
            [
                'product_id' => 12,
                'color' => 'Chocolate',
                'size' => '12 Lbs',
                'weight' => 5.44,
                'unit' => 'kg',
                'price' => 1800000.00,
                'discount_price' => null,
                'is_discounted' => false,
                'stock' => 20,
                'image_url' => 'https://res.cloudinary.com/dna9qbejm/image/upload/v1763044719/Shop_13_yii4wr.png',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // === 13. "Thanh Protein Zero Bar (20 thanh)" (product_id = 13) ===
            [
                'product_id' => 13,
                'color' => 'Chocolate Brownie', 
                'size' => 'Hộp 20 thanh',
                'weight' => 1.0,
                'unit' => 'kg',
                'price' => 1200000.00,
                'discount_price' => null,
                'is_discounted' => false,
                'stock' => 30,
                'image_url' => 'https://res.cloudinary.com/dna9qbejm/image/upload/v1763044394/Shop_12_thzsbf.png',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // === 14. "Giày Nike Metcon" (product_id = 14) ===
            [
                'product_id' => 14,
                'color' => 'Đen/Trắng',
                'size' => '41',
                'weight' => 0.8,
                'unit' => 'kg',
                'price' => 2800000.00,
                'discount_price' => null,
                'is_discounted' => false,
                'stock' => 10,
                'image_url' => 'https://res.cloudinary.com/dna9qbejm/image/upload/v1763044856/Shop_15_nckkgz.png',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 14,
                'color' => 'Đen/Trắng',
                'size' => '42',
                'weight' => 0.8,
                'unit' => 'kg',
                'price' => 2800000.00,
                'discount_price' => null,
                'is_discounted' => false,
                'stock' => 10,
                'image_url' => 'https://res.cloudinary.com/dna9qbejm/image/upload/v1763044856/Shop_15_nckkgz.png',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // === 15. "Bộ đồ tập Tracksuit" (product_id = 15) ===
            [
                'product_id' => 15,
                'color' => 'Xanh Navy',
                'size' => 'M',
                'weight' => 0.7,
                'unit' => 'kg',
                'price' => 1500000.00,
                'discount_price' => null,
                'is_discounted' => false,
                'stock' => 15,
                'image_url' => 'https://res.cloudinary.com/dna9qbejm/image/upload/v1763044855/Shop_14_dum3kn.png',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 15,
                'color' => 'Xanh Navy',
                'size' => 'L',
                'weight' => 0.7,
                'unit' => 'kg',
                'price' => 1500000.00,
                'discount_price' => null,
                'is_discounted' => false,
                'stock' => 15,
                'image_url' => 'https://res.cloudinary.com/dna9qbejm/image/upload/v1763044855/Shop_14_dum3kn.png',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // === 16. "Áo Thun Tập Gym Nam" (product_id = 16) ===
            [
                'product_id' => 16,
                'color' => 'Đen',
                'size' => 'L',
                'weight' => 0.2,
                'unit' => 'kg',
                'price' => 450000.00,
                'discount_price' => null,
                'is_discounted' => false,
                'stock' => 30,
                'image_url' => 'https://res.cloudinary.com/dna9qbejm/image/upload/v1763045685/Shop_19_mrlflt.png',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 16,
                'color' => 'Trắng',
                'size' => 'L',
                'weight' => 0.2,
                'unit' => 'kg',
                'price' => 450000.00,
                'discount_price' => null,
                'is_discounted' => false,
                'stock' => 30,
                'image_url' => 'https://res.cloudinary.com/dna9qbejm/image/upload/v1763045685/Shop_19_mrlflt.png',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // === 17. "Quần Short Tập Gym Nam 2 Lớp" (product_id = 17) ===
            [
                'product_id' => 17,
                'color' => 'Đen',
                'size' => 'L',
                'weight' => 0.3,
                'unit' => 'kg',
                'price' => 350000.00,
                'discount_price' => null,
                'is_discounted' => false,
                'stock' => 70,
                'image_url' => 'https://res.cloudinary.com/dna9qbejm/image/upload/v1763045160/Shop_16_hsewdx.png',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 17,
                'color' => 'Đen',
                'size' => 'XL',
                'weight' => 0.3,
                'unit' => 'kg',
                'price' => 350000.00,
                'discount_price' => null,
                'is_discounted' => false,
                'stock' => 70,
                'image_url' => 'https://res.cloudinary.com/dna9qbejm/image/upload/v1763045160/Shop_16_hsewdx.png',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // === 18. "Quần Legging Nữ Cạp Cao" (product_id = 18) ===
            [
                'product_id' => 18,
                'color' => 'Xám',
                'size' => 'M',
                'weight' => 0.25,
                'unit' => 'kg',
                'price' => 450000.00,
                'discount_price' => null,
                'is_discounted' => false,
                'stock' => 50,
                'image_url' => 'https://res.cloudinary.com/dna9qbejm/image/upload/v1763045366/Shop_17_pbgrsm.png',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 18,
                'color' => 'Xám',
                'size' => 'L',
                'weight' => 0.25,
                'unit' => 'kg',
                'price' => 450000.00,
                'discount_price' => null,
                'is_discounted' => false,
                'stock' => 50,
                'image_url' => 'https://res.cloudinary.com/dna9qbejm/image/upload/v1763045366/Shop_17_pbgrsm.png',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 18,
                'color' => 'Xám',
                'size' => 'XL',
                'weight' => 0.25,
                'unit' => 'kg',
                'price' => 450000.00,
                'discount_price' => null,
                'is_discounted' => false,
                'stock' => 40,
                'image_url' => 'https://res.cloudinary.com/dna9qbejm/image/upload/v1763045366/Shop_17_pbgrsm.png',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // === 19. "Set 4 Vớ Thể Thao" (product_id = 19) ===
            [
                'product_id' => 19,
                'color' => 'Trắng/Đen',
                'size' => 'Freesize',
                'weight' => 0.15,
                'unit' => 'kg',
                'price' => 120000.00,
                'discount_price' => null,
                'is_discounted' => false,
                'stock' => 100,
                'image_url' => 'https://res.cloudinary.com/dna9qbejm/image/upload/v1763045373/Shop_18_rid3r0.png',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // === 20. "Khăn tập Microfiber" (product_id = 20) ===
            [
                'product_id' => 20,
                'color' => 'Xanh Coban',
                'size' => '35x75cm',
                'weight' => 0.1,
                'unit' => 'kg',
                'price' => 99000.00,
                'discount_price' => null,
                'is_discounted' => false,
                'stock' => 100,
                'image_url' => 'https://res.cloudinary.com/dna9qbejm/image/upload/v1763045986/Shop_20_xh65nw.png',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // === 21. "Bình nước La Pro" (product_id = 21) ===
            [
                'product_id' => 21,
                'color' => 'Xanh nhạt',
                'size' => '1000ml',
                'weight' => 0.2,
                'unit' => 'kg',
                'price' => 109000.00,
                'discount_price' => null,
                'is_discounted' => false,
                'stock' => 150,
                'image_url' => 'https://res.cloudinary.com/dna9qbejm/image/upload/v1763045996/Shop_21_wwhld9.png',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 21,
                'color' => 'Hồng phấn',
                'size' => '1800ml',
                'weight' => 0.2,
                'unit' => 'kg',
                'price' => 179000.00,
                'discount_price' => null,
                'is_discounted' => false,
                'stock' => 150,
                'image_url' => 'https://res.cloudinary.com/dna9qbejm/image/upload/v1763057563/Shop_21_1_bae6y4.png',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 21,
                'color' => 'Đen',
                'size' => '1500ml',
                'weight' => 0.25,
                'unit' => 'kg',
                'price' => 149000.00,
                'discount_price' => null,
                'is_discounted' => false,
                'stock' => 100,
                'image_url' => 'https://res.cloudinary.com/dna9qbejm/image/upload/v1763057790/Shop_21_2_honaer.png',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // === 22. "Túi đựng đồ thể thao" (product_id = 22) ===
            [
                'product_id' => 22,
                'color' => 'Xám',
                'size' => 'Medium',
                'weight' => 0.5,
                'unit' => 'kg',
                'price' => 320000.00,
                'discount_price' => null,
                'is_discounted' => false,
                'stock' => 50,
                'image_url' => 'https://res.cloudinary.com/dna9qbejm/image/upload/v1763046038/Shop_22_phtubr.png',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // === 23. "Găng tay tập Gym" (product_id = 23) ===
            [
                'product_id' => 23,
                'color' => 'Đen',
                'size' => 'L',
                'weight' => 0.15,
                'unit' => 'kg',
                'price' => 250000.00,
                'discount_price' => null,
                'is_discounted' => false,
                'stock' => 40,
                'image_url' => 'https://res.cloudinary.com/dna9qbejm/image/upload/v1763046242/Shop_24_azlpqq.png',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // === 24. "Đai lưng mềm tập Gym" (product_id = 24) ===
            [
                'product_id' => 24,
                'color' => 'Đen',
                'size' => 'L',
                'weight' => 0.4,
                'unit' => 'kg',
                'price' => 380000.00,
                'discount_price' => null,
                'is_discounted' => false,
                'stock' => 30,
                'image_url' => 'https://res.cloudinary.com/dna9qbejm/image/upload/v1763046447/Shop_25_mbn0z8.png',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // === 25. "Băng bảo vệ gối" (product_id = 25) ===
            [
                'product_id' => 25,
                'color' => 'Đen',
                'size' => 'Freesize',
                'weight' => 0.2,
                'unit' => 'kg',
                'price' => 180000.00,
                'discount_price' => null,
                'is_discounted' => false,
                'stock' => 50,
                'image_url' => 'https://res.cloudinary.com/dna9qbejm/image/upload/v1763046235/Shop_23_bzi7dr.png',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}