<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Xóa sạch dữ liệu 
        DB::table('user')->truncate();

        // Tạo user 
        DB::table('user')->insert([
            // 3 user admin 
            [
                'full_name' => 'Nguyễn Văn An',
                'email' => 'an.nguyen@example.com',
                'password' => Hash::make('password123'),
                'role' => 'admin',
                'phone' => '0327123456',
                'birth_date' => '1989-04-12',
                'gender' => 'Nam',
                'address' => 'Số 12, Ngõ 45, Đường Trần Duy Hưng, Phường Trung Hòa, Thành phố Hà Nội', // ✅ Hợp lệ
                'image_url' => null,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Trần Thị Bích',
                'email' => 'bich.tran@example.com',
                'password' => Hash::make('password123'),
                'role' => 'admin',
                'phone' => '0912345678',
                'birth_date' => '1991-09-03',
                'gender' => 'Nữ',
                'address' => 'Căn hộ 7A, Tòa Ruby, Khu đô thị Vinhomes, Phường An Khánh, TP.HCM', // ✅ Hợp lệ (Phường An Khánh mới)
                'image_url' => null,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Lê Văn Mạnh',
                'email' => 'manh.le@example.com',
                'password' => Hash::make('password123'),
                'role' => 'admin',
                'phone' => '0987654321',
                'birth_date' => '1985-12-25',
                'gender' => 'Nam',
                'address' => 'Số 5, Đường Lê Lợi, Phường Bến Thành, Thành phố Hồ Chí Minh', // ✅ Hợp lệ (Phường Bến Thành mới)
                'image_url' => null,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // 7 user trainer
            [
                'full_name' => 'Lê Minh Châu',
                'email' => 'chau.le@example.com',
                'password' => Hash::make('123456'),
                'role' => 'trainer',
                'phone' => '0987654321',
                'birth_date' => '1992-06-15',
                'gender' => 'Nữ',
                'address' => 'Số 101, Đường Lê Hồng Phong, Phường Phước Ninh, Thành phố Đà Nẵng',
                'image_url' => null,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Phạm Văn Dũng',
                'email' => 'dung.pham@example.com',
                'password' => Hash::make('123456'),
                'role' => 'trainer',
                'phone' => '0938123456',
                'birth_date' => '1993-06-15',
                'gender' => 'Nam',
                'address' => '23/8, Đường Cách Mạng Tháng 8, Phường Võ Thị Sáu, TP.HCM',
                'image_url' => null,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Ngô Văn Đông',
                'email' => 'dong.ngo@example.com',
                'password' => Hash::make('123456'),
                'role' => 'trainer',
                'phone' => '0909123456',
                'birth_date' => '1990-12-20',
                'gender' => 'Nam',
                'address' => 'Số 56, Đường Điện Biên Phủ, Phường Điện Biên, Thành phố Hà Nội',
                'image_url' => null,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Nguyễn Thị Giang',
                'email' => 'giang.nguyen@example.com',
                'password' => Hash::make('123456'),
                'role' => 'trainer',
                'phone' => '0912345678',
                'birth_date' => '1994-03-22',
                'gender' => 'Nữ',
                'address' => 'Số 8, Khu 4, Đường Võ Văn Kiệt, Phường Cầu Ông Lãnh, TP.HCM',
                'image_url' => null,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Trương Minh Khanh',
                'email' => 'khanh.truong@example.com',
                'password' => Hash::make('123456'),
                'role' => 'trainer',
                'phone' => '0981234567',
                'birth_date' => '1988-11-11',
                'gender' => 'Nam',
                'address' => 'Số 45, Đường Nguyễn Văn Linh, Phường Hải Châu, Thành phố Đà Nẵng', // ✅ Hợp lệ (Phường Hải Châu mới)
                'image_url' => null,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Lê Thị Linh',
                'email' => 'linh.le@example.com',
                'password' => Hash::make('123456'),
                'role' => 'trainer',
                'phone' => '0912345678',
                'birth_date' => '1995-07-30',
                'gender' => 'Nữ',
                'address' => 'Số 12B, Khu phố 4, Phường Linh Xuân, TP.HCM',
                'image_url' => null,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Phạm Văn Minh',
                'email' => 'minh.pham@example.com',
                'password' => Hash::make('123456'),
                'role' => 'trainer',
                'phone' => '0987654321',
                'birth_date' => '1991-05-05',
                'gender' => 'Nam',
                'address' => 'Số 77, Đường Lý Thường Kiệt, Phường 14, TP.HCM',
                'image_url' => null,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // 10 user member
            [
                'full_name' => 'Vũ Thị Ngọc',
                'email' => 'ngoc.vu@example.com',
                'password' => Hash::make('userpass'),
                'role' => 'member',
                'phone' => '0901234567',
                'birth_date' => '1996-08-18',
                'gender' => 'Nữ',
                'address' => 'Số 22, Đường Trần Phú, Phường Điện Biên, Thành phố Hà Nội',
                'image_url' => null,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Đỗ Văn Phúc',
                'email' => 'phuc.do@example.com',
                'password' => Hash::make('userpass'),
                'role' => 'member',
                'phone' => '0912345678',
                'birth_date' => '1992-10-10',
                'gender' => 'Nam',
                'address' => 'Số 33, Đường Lý Thái Tổ, Phường Hàng Trống, Thành phố Hà Nội',
                'image_url' => null,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Trần Thị Quỳnh',
                'email' => 'quynh.tran@example.com',
                'password' => Hash::make('userpass'),
                'role' => 'member',
                'phone' => '0987654321',
                'birth_date' => '1994-02-14',
                'gender' => 'Nữ',
                'address' => 'Số 44, Đường Phan Đình Phùng, Phường Tân Định, TP.HCM',
                'image_url' => null,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Lý Văn Sang',
                'email' => 'sang.ly@example.com ',
                'password' => Hash::make('userpass'),
                'role' => 'member',
                'phone' => '0938123456',
                'birth_date' => '1993-09-09',
                'gender' => 'Nam',
                'address' => 'Số 55, Đường Hùng Vương, Phường Vĩnh Trung, Thành phố Đà Nẵng',
                'image_url' => null,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Phan Thị Thảo',
                'email' => 'thao.phan@example.com',
                'password' => Hash::make('userpass'),
                'role' => 'member',
                'phone' => '0909123456',
                'birth_date' => '1995-12-12',
                'gender' => 'Nữ',
                'address' => 'Số 66, Đường Trần Hưng Đạo, Phường Sài Gòn, TP.HCM',
                'image_url' => null,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Võ Văn Tiến',
                'email' => 'tien.vo@example.com',
                'password' => Hash::make('userpass'),
                'role' => 'member',
                'phone' => '0912345678',
                'birth_date' => '1991-03-03',
                'gender' => 'Nam',
                'address' => 'Số 77, Đường Lê Lợi, Phường Thạch Thang, Thành phố Đà Nẵng',
                'image_url' => null,
                'status' => 'inactive',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Đặng Thị Uyên',
                'email' => 'uyen.dang@example.com',
                'password' => Hash::make('userpass'),
                'role' => 'member',
                'phone' => '0987654321',
                'birth_date' => '1996-11-11',
                'gender' => 'Nữ',
                'address' => 'Số 88, Đường Nguyễn Huệ, Phường Sài Gòn, TP.HCM',
                'image_url' => null,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Trịnh Văn Bình',
                'email' => 'binh.trinh@example.com',
                'password' => Hash::make('userpass'),
                'role' => 'member',
                'phone' => '0938123456',
                'birth_date' => '1990-07-07',
                'gender' => 'Nam',
                'address' => 'Số 99, Đường Phạm Văn Đồng, Phường Mai Dịch, Thành phố Hà Nội',
                'image_url' => null,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Huỳnh Thị Cẩm',
                'email' => 'cam.huynh@example.com',
                'password' => Hash::make('userpass'),
                'role' => 'member',
                'phone' => '0901234567',
                'birth_date' => '1997-04-04',
                'gender' => 'Nữ',
                'address' => 'Số 100, Đường Lý Chính Thắng, Phường Võ Thị Sáu, TP.HCM',
                'image_url' => null,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Nguyễn Văn Hùng',
                'email' => 'hung.nguyen@example.com',
                'password' => Hash::make('userpass'),
                'role' => 'member',
                'phone' => '0912345678',
                'birth_date' => '1998-01-01',
                'gender' => 'Nam',
                'address' => 'Số 111, Đường Trần Quang Khải, Phường Tân Định, TP.HCM',
                'image_url' => null,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}