<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Xóa sạch dữ liệu 
        DB::table('user')->truncate();

        // Tạo user 
        DB::table('user')->insert([
            // 3 user admin 
            [
                'full_name' => 'Nguyễn Văn An',
                'email' => 'an.nguyen@example.com',
                'password' => Hash::make('password123'),
                'role' => 'admin',
                'phone' => '0327123456',
                'birth_date' => '1989-04-12',
                'gender' => 'Nam',
                'address' => 'Số 12, Ngõ 45, Đường Trần Duy Hưng, Phường Trung Hòa, Thành phố Hà Nội',
                'image_url' => null,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Trần Thị Bích',
                'email' => 'bich.tran@example.com',
                'password' => Hash::make('password123'),
                'role' => 'admin',
                'phone' => '0912345678',
                'birth_date' => '1991-09-03',
                'gender' => 'Nữ',
                'address' => 'Căn hộ 7A, Tòa Ruby, Khu đô thị Vinhomes, Phường An Khánh, TP.HCM',
                'image_url' => null,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Lê Văn Mạnh',
                'email' => 'manh.le@example.com',
                'password' => Hash::make('password123'),
                'role' => 'admin',
                'phone' => '0987654321',
                'birth_date' => '1985-12-25',
                'gender' => 'Nam',
                'address' => 'Số 5, Đường Lê Lợi, Phường Bến Thành, Thành phố Hồ Chí Minh',
                'image_url' => null,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // 7 user trainer (CŨ)
            [
                'full_name' => 'Lê Minh Châu',
                'email' => 'chau.le@example.com',
                'password' => Hash::make('123456'),
                'role' => 'trainer',
                'phone' => '0987654321',
                'birth_date' => '1992-06-15',
                'gender' => 'Nữ',
                'address' => 'Số 101, Đường Lê Hồng Phong, Phường Phước Ninh, Thành phố Đà Nẵng',
                'image_url' => null,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Phạm Văn Dũng',
                'email' => 'dung.pham@example.com',
                'password' => Hash::make('123456'),
                'role' => 'trainer',
                'phone' => '0938123456',
                'birth_date' => '1993-06-15',
                'gender' => 'Nam',
                'address' => '23/8, Đường Cách Mạng Tháng 8, Phường Võ Thị Sáu, TP.HCM',
                'image_url' => null,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Ngô Văn Đông',
                'email' => 'dong.ngo@example.com',
                'password' => Hash::make('123456'),
                'role' => 'trainer',
                'phone' => '0909123456',
                'birth_date' => '1990-12-20',
                'gender' => 'Nam',
                'address' => 'Số 56, Đường Điện Biên Phủ, Phường Điện Biên, Thành phố Hà Nội',
                'image_url' => null,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Nguyễn Thị Giang',
                'email' => 'giang.nguyen@example.com',
                'password' => Hash::make('123456'),
                'role' => 'trainer',
                'phone' => '0912345678',
                'birth_date' => '1994-03-22',
                'gender' => 'Nữ',
                'address' => 'Số 8, Khu 4, Đường Võ Văn Kiệt, Phường Cầu Ông Lãnh, TP.HCM',
                'image_url' => null,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Trương Minh Khanh',
                'email' => 'khanh.truong@example.com',
                'password' => Hash::make('123456'),
                'role' => 'trainer',
                'phone' => '0981234567',
                'birth_date' => '1988-11-11',
                'gender' => 'Nam',
                'address' => 'Số 45, Đường Nguyễn Văn Linh, Phường Hải Châu, Thành phố Đà Nẵng',
                'image_url' => null,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Lê Thị Linh',
                'email' => 'linh.le@example.com',
                'password' => Hash::make('123456'),
                'role' => 'trainer',
                'phone' => '0912345678',
                'birth_date' => '1995-07-30',
                'gender' => 'Nữ',
                'address' => 'Số 12B, Khu phố 4, Phường Linh Xuân, TP.HCM',
                'image_url' => null,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Phạm Văn Minh',
                'email' => 'minh.pham@example.com',
                'password' => Hash::make('123456'),
                'role' => 'trainer',
                'phone' => '0987654321',
                'birth_date' => '1991-05-05',
                'gender' => 'Nam',
                'address' => 'Số 77, Đường Lý Thường Kiệt, Phường 14, TP.HCM',
                'image_url' => null,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // 14 user trainer 
            // CN Võ Thị Sáu
            [
                'full_name' => 'Trần Văn Hoàng',
                'email' => 'hoang.tran@example.com',
                'password' => Hash::make('123456'),
                'role' => 'trainer',
                'phone' => '0911111111',
                'birth_date' => '1995-01-10',
                'gender' => 'Nam',
                'address' => 'Số 210, Đường Nguyễn Đình Chiểu, Phường Võ Thị Sáu, TP.HCM', 
                'image_url' => null,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Nguyễn Thị Kim Anh',
                'email' => 'kimanh.nguyen@example.com',
                'password' => Hash::make('123456'),
                'role' => 'trainer',
                'phone' => '0911111112',
                'birth_date' => '1996-03-20',
                'gender' => 'Nữ',
                'address' => 'Căn hộ 15A, Chung cư 90, Đường Trương Định, Phường Võ Thị Sáu, TP.HCM', 
                'image_url' => null,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // CN Lý Thường Kiệt
            [
                'full_name' => 'Lê Minh Hùng',
                'email' => 'hung.le@example.com',
                'password' => Hash::make('123456'),
                'role' => 'trainer',
                'phone' => '0911111113',
                'birth_date' => '1993-11-05',
                'gender' => 'Nam',
                'address' => 'Số 45, Đường Bàu Cát, Phường 14, TP.HCM', 
                'image_url' => null,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Võ Thị Hồng',
                'email' => 'hong.vo@example.com',
                'password' => Hash::make('123456'),
                'role' => 'trainer',
                'phone' => '0911111114',
                'birth_date' => '1997-07-07',
                'gender' => 'Nữ',
                'address' => '120/5B, Đường Trường Chinh, Phường 14, TP.HCM',
                'image_url' => null,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // CN Linh Xuân
            [
                'full_name' => 'Phạm Hoàng Long',
                'email' => 'long.pham@example.com',
                'password' => Hash::make('123456'),
                'role' => 'trainer',
                'phone' => '0911111115',
                'birth_date' => '1990-02-15',
                'gender' => 'Nam',
                'address' => 'Số 55, Đường số 5, Khu phố 4, Phường Linh Xuân, TP.HCM',
                'image_url' => null,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Đặng Thu Thảo',
                'email' => 'thaodang@example.com',
                'password' => Hash::make('123456'),
                'role' => 'trainer',
                'phone' => '0911111116',
                'birth_date' => '1998-05-25',
                'gender' => 'Nữ',
                'address' => '88A, Quốc lộ 1K, Khu phố 3, Phường Linh Xuân, TP.HCM',
                'image_url' => null,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // CN Điện Biên (HN)
            [
                'full_name' => 'Hoàng Văn Trung',
                'email' => 'trung.hoang@example.com',
                'password' => Hash::make('123456'),
                'role' => 'trainer',
                'phone' => '0911111117',
                'birth_date' => '1992-08-30',
                'gender' => 'Nam',
                'address' => 'Số 60, Đường Điện Biên Phủ, Phường Điện Biên, Thành phố Hà Nội', 
                'image_url' => null,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Ngô Bảo Châu',
                'email' => 'chau.ngo@example.com',
                'password' => Hash::make('123456'),
                'role' => 'trainer',
                'phone' => '0911111118',
                'birth_date' => '1994-04-01',
                'gender' => 'Nữ',
                'address' => 'Căn hộ 301, Tòa A, 19C Đường Hoàng Diệu, Phường Điện Biên, Thành phố Hà Nội', 
                'image_url' => null,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // CN Hoàng Diệu (HN)
            [
                'full_name' => 'Vũ Tuấn Kiệt',
                'email' => 'kiet.vu@example.com',
                'password' => Hash::make('123456'),
                'role' => 'trainer',
                'phone' => '0911111119',
                'birth_date' => '1991-10-10',
                'gender' => 'Nam',
                'address' => 'Số 14, Đường Nguyễn Tri Phương, Phường Điện Biên, Thành phố Hà Nội', 
                'image_url' => null,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Hà Kiều Trang',
                'email' => 'trang.ha@example.com',
                'password' => Hash::make('123456'),
                'role' => 'trainer',
                'phone' => '0911111120',
                'birth_date' => '1996-12-01',
                'gender' => 'Nữ',
                'address' => 'Số 9A, Ngõ 4, Đường Tôn Thất Thiệp, Phường Điện Biên, Thành phố Hà Nội', 
                'image_url' => null,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // CN Trung Hòa (HN)
            [
                'full_name' => 'Nguyễn Minh Quân',
                'email' => 'quan.nguyen@example.com',
                'password' => Hash::make('123456'),
                'role' => 'trainer',
                'phone' => '0911111121',
                'birth_date' => '1989-06-18',
                'gender' => 'Nam',
                'address' => 'Tòa 24T1, Đường Trần Duy Hưng, Phường Trung Hòa, Thành phố Hà Nội', 
                'image_url' => null,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Lý Thanh Thảo',
                'email' => 'thao.ly@example.com',
                'password' => Hash::make('123456'),
                'role' => 'trainer',
                'phone' => '0911111122',
                'birth_date' => '1995-09-19',
                'gender' => 'Nữ',
                'address' => 'Số 33, Ngõ 110, Đường Nguyễn Thị Định, Phường Trung Hòa, Thành phố Hà Nội', 
                'image_url' => null,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // CN Phước Ninh (DN)
            [
                'full_name' => 'Đinh Tiến Đạt',
                'email' => 'dat.dinh@example.com',
                'password' => Hash::make('123456'),
                'role' => 'trainer',
                'phone' => '0911111123',
                'birth_date' => '1993-04-25',
                'gender' => 'Nam',
                'address' => 'Số 250, Đường Trần Phú, Phường Phước Ninh, Thành phố Đà Nẵng',
                'image_url' => null,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Mai Phương Anh',
                'email' => 'anh.mai@example.com',
                'password' => Hash::make('123456'),
                'role' => 'trainer',
                'phone' => '0911111124',
                'birth_date' => '1997-11-30',
                'gender' => 'Nữ',
                'address' => 'K14/22, Đường Nguyễn Văn Linh, Phường Nam Dương, Thành phố Đà Nẵng', 
                'image_url' => null,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // 10 user member
            [
                'full_name' => 'Vũ Thị Ngọc',
                'email' => 'ngoc.vu@example.com',
                'password' => Hash::make('userpass'),
                'role' => 'member',
                'phone' => '0901234567',
                'birth_date' => '1996-08-18',
                'gender' => 'Nữ',
                'address' => 'Số 22, Đường Trần Phú, Phường Điện Biên, Thành phố Hà Nội',
                'image_url' => null,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Đỗ Văn Phúc',
                'email' => 'phuc.do@example.com',
                'password' => Hash::make('userpass'),
                'role' => 'member',
                'phone' => '0912345678',
                'birth_date' => '1992-10-10',
                'gender' => 'Nam',
                'address' => 'Số 33, Đường Lý Thái Tổ, Phường Hàng Trống, Thành phố Hà Nội',
                'image_url' => null,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Trần Thị Quỳnh',
                'email' => 'quynh.tran@example.com',
                'password' => Hash::make('userpass'),
                'role' => 'member',
                'phone' => '0987654321',
                'birth_date' => '1994-02-14',
                'gender' => 'Nữ',
                'address' => 'Số 44, Đường Phan Đình Phùng, Phường Tân Định, TP.HCM',
                'image_url' => null,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Lý Văn Sang',
                'email' => 'sang.ly@example.com ',
                'password' => Hash::make('userpass'),
                'role' => 'member',
                'phone' => '0938123456',
                'birth_date' => '1993-09-09',
                'gender' => 'Nam',
                'address' => 'Số 55, Đường Hùng Vương, Phường Vĩnh Trung, Thành phố Đà Nẵng',
                'image_url' => null,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Phan Thị Thảo',
                'email' => 'thao.phan@example.com',
                'password' => Hash::make('userpass'),
                'role' => 'member',
                'phone' => '0909123456',
                'birth_date' => '1995-12-12',
                'gender' => 'Nữ',
                'address' => 'Số 66, Đường Trần Hưng Đạo, Phường Sài Gòn, TP.HCM',
                'image_url' => null,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Võ Văn Tiến',
                'email' => 'tien.vo@example.com',
                'password' => Hash::make('userpass'),
                'role' => 'member',
                'phone' => '0912345678',
                'birth_date' => '1991-03-03',
                'gender' => 'Nam',
                'address' => 'Số 77, Đường Lê Lợi, Phường Thạch Thang, Thành phố Đà Nẵng',
                'image_url' => null,
                'status' => 'inactive',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Đặng Thị Uyên',
                'email' => 'uyen.dang@example.com',
                'password' => Hash::make('userpass'),
                'role' => 'member',
                'phone' => '0987654321',
                'birth_date' => '1996-11-11',
                'gender' => 'Nữ',
                'address' => 'Số 88, Đường Nguyễn Huệ, Phường Sài Gòn, TP.HCM',
                'image_url' => null,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Trịnh Văn Bình',
                'email' => 'binh.trinh@example.com',
                'password' => Hash::make('userpass'),
                'role' => 'member',
                'phone' => '0938123456',
                'birth_date' => '1990-07-07',
                'gender' => 'Nam',
                'address' => 'Số 99, Đường Phạm Văn Đồng, Phường Mai Dịch, Thành phố Hà Nội',
                'image_url' => null,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Huỳnh Thị Cẩm',
                'email' => 'cam.huynh@example.com',
                'password' => Hash::make('userpass'),
                'role' => 'member',
                'phone' => '0901234567',
                'birth_date' => '1997-04-04',
                'gender' => 'Nữ',
                'address' => 'Số 100, Đường Lý Chính Thắng, Phường Võ Thị Sáu, TP.HCM',
                'image_url' => null,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Nguyễn Văn Hùng',
                'email' => 'hung.nguyen@example.com',
                'password' => Hash::make('userpass'),
                'role' => 'member',
                'phone' => '0912345678',
                'birth_date' => '1998-01-01',
                'gender' => 'Nam',
                'address' => 'Số 111, Đường Trần Quang Khải, Phường Tân Định, TP.HCM',
                'image_url' => null,
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // HLV nghỉ việc
            [
                'full_name' => 'Trần Văn Khoa',
                'email' => 'khoa.tran@example.com',
                'password' => Hash::make('123456'),
                'role' => 'trainer',
                'phone' => '0909988776',
                'birth_date' => '1985-05-15',
                'gender' => 'Nam',
                'address' => 'Số 200, Đường Lý Thường Kiệt, Phường 14, TP.HCM',
                'image_url' => null,
                'status' => 'inactive',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}